### ISSUE TITLE
Bombay error

### ISSUE THREAD

**Issue by invis87** [terra-money/LocalTerra#23]
Node is exited immediately after start.
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                      PORTS                                       NAMES
4a873e3c5211   terramoney/pseudo-feeder:bombay     "npm run start"          33 seconds ago   Up 28 seconds                                                           localterra_oracle_1
46d9092b9ebc   terramoney/fcd:bombay               "./entrypoint.sh sta…"   33 seconds ago   Up 26 seconds               0.0.0.0:3060->3060/tcp, :::3060->3060/tcp   localterra_fcd-api_1
1b129e59eb77   terramoney/fcd:bombay               "./entrypoint.sh col…"   33 seconds ago   Exited (0) 11 seconds ago                                               localterra_fcd-collector_1
6af3f09f478a   postgres:12                         "docker-entrypoint.s…"   37 seconds ago   Up 34 seconds               5432/tcp                                    localterra_postgres_1
846612bb35c0   terramoney/localterra-core:bombay   "terrad start"           37 seconds ago   Exited (2) 32 seconds ago                                               localterra_terrad_1
```

logs for `terrad`:
```
~/scripts/test-contract ➜ docker logs 846612bb35c0
8:44PM INF starting ABCI with Tendermint
8:44PM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:44PM INF Starting localClient service connection=query impl=localClient module=abci-client
8:44PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:44PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:44PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:44PM INF Starting EventBus service impl=EventBus module=events
8:44PM INF Starting PubSub service impl=PubSub module=pubsub
8:44PM INF Starting IndexerService service impl=IndexerService module=txindex
8:44PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.0-rc0
8:44PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "max_contract_data_size" in types.Params

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc000f97650, 0xc0010b83c0, 0x1ca, 0x1e0, 0x2c4bc30, 0xc000fd42a0)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/codec/proto_codec.go:176 +0x98
github.com/terra-money/core/x/wasm.AppModule.InitGenesis(0x2c70e18, 0xc000f97650, 0x2c35198, 0xc000533230, 0x2c6b178, 0xc000f97650, 0x2c6b178, 0xc000f97650, 0xc000fca128, 0x2c35198, ...)
        github.com/terra-money/core/x/wasm/module.go:149 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000542150, 0x2c538e8, 0xc00013a040, 0x2c6dd60, 0xc000f98300, 0x0, 0x0, 0xc0000c59f0, 0xa, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/types/module/module.go:306 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc000f37b00, 0x2c538e8, 0xc00013a040, 0x2c6dd60, 0xc000f98300, 0x0, 0x0, 0xc0000c59f0, 0xa, 0x0, ...)
        github.com/terra-money/core/app/app.go:614 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000128000, 0x17a67180, 0xed840139e, 0x0, 0xc0000c59f0, 0xa, 0xc0006863c0, 0x3c24490, 0x0, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000d2d020, 0x17a67180, 0xed840139e, 0x0, 0xc0000c59f0, 0xa, 0xc0006863c0, 0x3c24490, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000f97570, 0x17a67180, 0xed840139e, 0x0, 0xc0000c59f0, 0xa, 0xc0006863c0, 0x3c24490, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000ccdc18, 0xb, 0x0, 0x25004ad, 0x7, 0xc0000c59f0, 0xa, 0x1, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000ccdc18, 0x2c6f068, 0xc000c455f0, 0x1f4, 0xc0012a1880)
        github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x2c6ac38, 0xc000f966e0, 0xb, 0x0, 0x25004ad, 0x7, 0xc0000c59f0, 0xa, 0x1, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0010d4500, 0x2c48a50, 0xc0005448c0, 0xc000f1d920, 0x2c11620, 0xc00113b920, 0xc000f1da80, 0x29e63a8, 0xc000f1db70, 0x2c545d0, ...)
        github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x20e5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0010b02a0, 0x0, 0x0, 0x0, 0x2c785d8, 0xc0010ec1b0, 0xc001045d70, 0xa, 0x2c5db90, 0xc000f97650, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/server/start.go:261 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001018a00, 0x3c24490, 0x0, 0x0, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc001018a00, 0x3c24490, 0x0, 0x0, 0xc001018a00, 0x3c24490)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cf5900, 0x0, 0x0, 0xc000f8cbc0)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000cf5900, 0xc000f8cbc0, 0xc, 0x2c70e18, 0xc000f97650)
        github.com/cosmos/cosmos-sdk@v0.43.0-rc0/server/cmd/execute.go:36 +0x285
main.main()
        github.com/terra-money/core/cmd/terrad/main.go:15 +0x45
```

logs for `fcd`:
```
~/scripts/test-contract ➜ docker logs 1b129e59eb77

> fcd@1.0.0-alpha.7 apidoc /app
> ts-node -T --files -r tsconfig-paths/register src/scripts/generateApidoc.ts

/app/apidoc-template/index.html
/app/static/index.html

> fcd@1.0.0-alpha.7 mergeswagger /app
> ts-node -T --files -r tsconfig-paths/register src/scripts/mergeSwaggerFile.ts "-o" "swagger.json"

RequestError: Error: getaddrinfo ENOTFOUND terrad
    at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.emit (domain.js:470:12)
    at Request.onRequestError (/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:376:20)
    at ClientRequest.emit (domain.js:470:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: getaddrinfo ENOTFOUND terrad
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'terrad'
  },
  error: Error: getaddrinfo ENOTFOUND terrad
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'terrad'
  },
  options: {
    uri: 'http://terrad:1317/swagger/swagger.yaml',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

> fcd@1.0.0-alpha.7 collector /app
> better-npm-run collector-prod

running better-npm-run in /app
Executing script: collector-prod

to be executed: node --stack_size=4096 --max-old-space-size=4096 -r ts-node/register/transpile-only -r tsconfig-paths/register src/collector/collector.ts
no token info for this chain-id
```

**Comment by invis87** [comment]
partially solved by https://github.com/terra-money/LocalTerra/pull/25
